name: Playwright Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start services using Docker Compose
        run: docker-compose up -d --build
        working-directory: ./

      # - name: Check Docker container logs (Frontend)
      #   if: always()
      #   run: docker-compose logs frontend

      # - name: Check Docker container logs (Backend)
      #   if: always()
      #   run: docker-compose logs backend

      - name: Install Playwright dependencies
        run: npm ci
        working-directory: ./qa

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./qa

      - name: Run Playwright tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npx playwright test
        working-directory: ./qa

      # - name: Run Playwright tests
      #   run: npx playwright test
      #   working-directory: ./qa

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-screenshots
          path: ./qa/screenshots/

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: ./qa/playwright-report/
          retention-days: 30

      - name: Stop and remove services
        if: always()
        run: docker-compose down
        working-directory: ./
